### ISSUE TITLE
Black keyboard buttons (non-themed)

### ISSUE THREAD

**Issue by MasterGroosha** [jacklul/inlinegamesbot#1]
Hi there! There's a very strange issue with your bot.

Here are how text looks with your bot (Tic-Tac-Toe game)
![image](https://cloud.githubusercontent.com/assets/2780044/23590121/4ea6452c-01eb-11e7-82a4-7127e4cbb5f0.png)

And here's how all other bots show keyboard (white color is set in theme)
![image](https://cloud.githubusercontent.com/assets/2780044/23590124/62cab45c-01eb-11e7-8fe6-87c5379fd3bf.png)

Because of ` ` symbol (space?) TDesktop doesn't color buttons.
I'll report this to TDesktop repo as well, however, please look if you can do something about it.

**Comment by jacklul** [comment]
Well, someone at [tdesktop](https://github.com/telegramdesktop/tdesktop) forgot there can be only whitespace character in the button text, as a temporary fix I replaced space with a dot.

Thanks for the info!
