### ISSUE TITLE
Bot is very slow/does rarely respond

### ISSUE THREAD

**Issue by Jak0p** [jacklul/inlinegamesbot#10]
Hey, 
I always liked that bot (especially connect four). Now I wasn't playing for some weeks and today the bot isn't really responding to my input. 
Can you maybe restart the bot or something like that? 

Thanks for your work!

**Comment by jacklul** [comment]
That's probably because it's getting flooded with popularity and my server can't handle it.

**Comment by jacklul** [comment]
@Jak0p is it slightly better now?

**Comment by Jak0p** [comment]
Was trying it just now and it was way better! Actually it was totally fluent again. I will have an eye on it the next days ;) 
Did you upgrade your server?

**Comment by jacklul** [comment]
@Jak0p Just applied few tweaks, it turns out database was at fault, limiting connections...
