### ISSUE TITLE
Bug in Rock-Paper-Scissors score

### ISSUE THREAD

**Issue by DO97** [jacklul/inlinegamesbot#11]
4th round, I scored the 2-1. The game automatically ended, but it was possible a draw.

![screenshot_20180226-232042](https://user-images.githubusercontent.com/17525578/36699488-1372ede4-1b4d-11e8-8810-cb743f1e33a7.jpg)

**Comment by jacklul** [comment]
@DO97 Applied quick fix, first player to get to 3 points should win, draw give no points

**Comment by DO97** [comment]
It seems ok now. Thank you @jacklul 
Previously, in case of 2-0 after the 4th round, the game automatically stopped. Maybe, this combination could remain like that.
There was only a bug with the 2-1 after the 4th round.
