### ISSUE TITLE
Connect Four bug

### ISSUE THREAD

**Issue by ghost** [jacklul/inlinegamesbot#12]
hi, while I was playing connect four with a friend, I noticed a bug in the seventh column
![img_20180812_135208](https://user-images.githubusercontent.com/32811183/44001728-652678d2-9e37-11e8-8fdd-9ae9de0c43a1.png)

my friend won, but first I had put four vertical balls in the seventh column
we tried to recreate the error by noting that it only happens in the seventh column
(sorry for the bad English, I'm Italian)

**Comment by jacklul** [comment]
Should be fixed now
