### ISSUE TITLE
Russian roulette

### ISSUE THREAD

**Issue by Hunter1212** [jacklul/inlinegamesbot#16]
How does the game work? I tried playing it with my friend and it kept saying survived for both of us forever, we noticed after our 8th attempt at it.

**Comment by jacklul** [comment]
@Hunter1212 One of the chambers has a bullet in it, the position changes each round.

**Comment by Hunter1212** [comment]
@jacklul But doesn't it like meant to be as such that each round the probability changes. Like when it fires first there's 1/6 chances for the bullet and 5/6 chances to survive. The next turn it changes to 1/5 for the other player and it keeps decreasing. Or that's how I thought the game was supposed to be.

So the game keeps on continuing as long as both players keep surviving with a 5/6 surviving chances or 83% chances of you surviving each round?

**Comment by jacklul** [comment]
@Hunter1212 Correct.
