### ISSUE TITLE
Simple Dunnos

### ISSUE THREAD

**Issue by inukaze** [jacklul/inlinegamesbot#17]
1 - How i can play in single player mode ?
2 - You can Add Tetris or Tengen Tetris ?

**Comment by jacklul** [comment]
There is no single player mode.
Implementing Tetris would require server to run a 'game process' per each user which would be very costly to mantain.

PS. I believe there is/was already Tetris bot on Telegram, I do not remember it's username.

**Comment by inukaze** [comment]
Thanks for the quick answer. well is sad can't play in single player mode. if you remember the name of tetris bot game for telegram specially if inline, tell me plz :)
