### ISSUE TITLE
Deploy heroku not working

### ISSUE THREAD

**Issue by c3bola** [jacklul/inlinegamesbot#21]
When deploying to Heroku, the following error occurs

/bin/sh: 1: php bin/console install,php bin/console set: not found

**Comment by c3bola** [comment]
Build app log



-----> Building on the Heroku-20 stack

-----> Deleting 2 files matching .slugignore patterns.

-----> Using buildpack: https://github.com/heroku/heroku-buildpack-php

-----> PHP app detected

-----> Bootstrapping...

-----> Installing platform packages...

       - php (7.4.21)

       - ext-gettext (bundled with php)

       - ext-intl (bundled with php)

       - ext-mbstring (bundled with php)

       - composer (2.1.3)

       - apache (2.4.48)

       - nginx (1.20.1)

-----> Installing dependencies...

       Composer version 2.1.3 2021-06-09 16:31:20

       Installing dependencies from lock file

       Verifying lock file contents can be installed on current platform.

       Package operations: 13 installs, 0 updates, 0 removals

         - Downloading gettext/languages (2.6.0)

         - Downloading gettext/gettext (v4.8.4)

         - Downloading guzzlehttp/promises (1.4.1)

         - Downloading ralouphie/getallheaders (3.0.3)

         - Downloading psr/http-message (1.0.1)

         - Downloading guzzlehttp/psr7 (1.8.2)

         - Downloading psr/log (1.1.4)

         - Downloading monolog/monolog (2.2.0)

         - Downloading jacklul/monolog-telegram (2.0.0)

         - Downloading psr/http-client (1.0.1)

         - Downloading guzzlehttp/guzzle (7.3.0)

         - Downloading longman/telegram-bot (0.73.1)

         - Downloading spatie/emoji (2.3.0)

         - Installing gettext/languages (2.6.0): Extracting archive

         - Installing gettext/gettext (v4.8.4): Extracting archive

         - Installing guzzlehttp/promises (1.4.1): Extracting archive

         - Installing ralouphie/getallheaders (3.0.3): Extracting archive

         - Installing psr/http-message (1.0.1): Extracting archive

         - Installing guzzlehttp/psr7 (1.8.2): Extracting archive

         - Installing psr/log (1.1.4): Extracting archive

         - Installing monolog/monolog (2.2.0): Extracting archive

         - Installing jacklul/monolog-telegram (2.0.0): Extracting archive

         - Installing psr/http-client (1.0.1): Extracting archive

         - Installing guzzlehttp/guzzle (7.3.0): Extracting archive

         - Installing longman/telegram-bot (0.73.1): Extracting archive

         - Installing spatie/emoji (2.3.0): Extracting archive

       Generating optimized autoload files

       5 packages you are using are looking for funding.

       Use the `composer fund` command to find out more!

-----> Preparing runtime environment...

-----> Checking for additional extensions to install...

-----> Discovering process types

       Procfile declares types -> web

-----> Compressing...

       Done: 15M

-----> Launching...

       Released v7

       https://fortgamebot.herokuapp.com/ deployed to Heroku

**Comment by jacklul** [comment]
Can you try again using this [deploy link](https://heroku.com/deploy?template=https://github.com/jacklul/inlinegamesbot/tree/develop)?
I've changed app.json on develop that might make it work

**Comment by c3bola** [comment]
I just took the test and the error remains the same

These are the data I used
**Admin's Telegram ID:** 121823278
**BOT_TOKEN:** ok
 **BOT_USERNAME:** FortniteBrGameBot
 **BOT_WEBHOOK:** https://fortnitebrgamebot.herokuapp.com

**Comment by jacklul** [comment]
It has nothing to do with what you entered, it seems like postdeploy script isn't working as intended or I configured it wrong.
Will continue investigating

**Comment by jacklul** [comment]
It should be working now through the deploy link I sent earlier

**Comment by c3bola** [comment]
nice work!
Thank you for your patience
