### ISSUE TITLE
lunch without heroku

### ISSUE THREAD

**Issue by 98rostami** [jacklul/inlinegamesbot#23]
Hello 
How can I install this robot on a personal host?
Which file should I set webhook?
Thanks very much

**Comment by jacklul** [comment]
It should work but I don't have any specific instructions other than these tips:

- Take a look at the .env.example file, copy it into .env then fill out the config variables
_You will want to uncomment `DATABASE_URL` variable and insert DSN string for database connection (Mysql/PSQL), when left commented out/empty will use a flat file as database (not recommended)_

- The webhook should point at the public directory

**Comment by 98rostami** [comment]
Hello thanks for your answer

**Comment by jacklul** [comment]
> I couldnt install on my host because i couldnt create DSN string for mysql

Example DSN:
```
mysql://USER:PASSWORD@HOST:PORT/DATABASE
```

> I fork your git and want add a language file(persian) how can do this?

Create new file in translations folder using gettext compatible editor (I used Poedit) based off `messages.pot` file (that file has to be set as "base" in the editor). I believe once you open `messages.pot` with Poedit it will give you an option "Create new translations" and then guide you through the process.
There is a chance that the base file is a bit of out of date and you will need to run a rescan in the editor.
Keep in mind that translations is not something that was fully implemented in the bot - it might not work at all.

**Comment by jacklul** [comment]
Closed in favor of #24
