### ISSUE TITLE
language of the robot

### ISSUE THREAD

**Issue by 98rostami** [jacklul/inlinegamesbot#24]
I forked the project then i translated the messages.pot file in poedit and uploaded the translation file
In the file /src/Helper/Language.php I changed the following variables to fa_IR
$default_language
$current_language
Then I did a deploy in heroku, but the bot language is still English!
For the test, the word Hi! At /src/Command/UserStartCommand.php i do replaced to Hello without changing it in the messages.pot file and the bot displays Hello! 
This means that the language file is not applied at all!
What exactly should I do to make the bot language Persian?
Thank you for your answer

**Comment by jacklul** [comment]
I've updated the source code, take a look at the develop branch.

The translation procedure should look like this:
- Poedit > File -> Create new from POT file -> select `messages.pot` from the file browser -> select target language
- Translate
- Save the file as messages.XX.po, where XX is language code
- To force default language set environment variable (or in .env) `DEFAULT_LANGUAGE=XX`
- It should be working at this point

**Comment by pavanyogi** [comment]
We are using the example-bot code as a starter code. I tried to follow the above steps in order to make the bot multilingual. But we got some errors. 

**Commands/StartCommand.php**

```php
public function execute(): ServerResponse
{
    $this->getMessage()->getText(true);

    return $this->replyToChat(
        '<b>' . __('Hi!') . '</b>' . PHP_EOL .
        'Type /help to see all commands!'
    );
}
```
**Error:**
```sh
PHP Fatal error:  Uncaught Error: Call to undefined function Longman\\TelegramBot\\Commands\\SystemCommands\\__() in /home/pavany/Documents/aux/qbix/telegram-bot/example-bot/Commands/Custom/StartCommand.php:103\nStack trace:\n#0 /home/pavany/Documents/aux/qbix/telegram-bot/example-bot/vendor/longman/telegram-bot/src/Commands/Command.php(197): Longman\\TelegramBot\\Commands\\SystemCommands\\StartCommand->execute()\n#1 /home/pavany/Documents/aux/qbix/telegram-bot/example-bot/vendor/longman/telegram-bot/src/Telegram.php(674): Longman\\TelegramBot\\Commands\\Command->preExecute()\n#2 /home/pavany/Documents/aux/qbix/telegram-bot/example-bot/vendor/longman/telegram-bot/src/Telegram.php(646): Longman\\TelegramBot\\Telegram->executeCommand('start')\n#3 /home/pavany/Documents/aux/qbix/telegram-bot/example-bot/vendor/longman/telegram-bot/src/Telegram.php(557): Longman\\TelegramBot\\Telegram->processUpdate(Object(Longman\\TelegramBot\\Entities\\Update))\n#4 /home/pavany/Documents/aux/qbix/telegram-bot/example-bot/vendor/php-telegram-bot/telegram-bot-manager/src in /home/pavany/Documents/aux/qbix/telegram-bot/example-bot/Commands/Custom/StartCommand.php on line 103
```
I think it might be related to auto loading, etc?

**Comment by jacklul** [comment]
The translation support in this project is using handcrafted class - [/src/Helper/Language.php](https://github.com/jacklul/inlinegamesbot/blob/master/src/Helper/Language.php) and [gettext](https://packagist.org/packages/gettext/gettext) library.

The error is caused by not having global `__()` function registered from the mentioned library.
