### ISSUE TITLE
Translations is not work

### ISSUE THREAD

**Issue by thescs** [jacklul/inlinegamesbot#30]
Hello. Translations don't work for me.
I uncommented the .env line, translated the file, renamed it to **messages.ru.po**, wrote
DEFAULT_LANGUAGE=ru

But the language is still English.

**Comment by jacklul** [comment]
Use gettext-compatible translation software (Poedit works great), load .pot file into it and then use "create new translation" option, then save the translation as the file name you mentioned, then it "should" work.
I'm pretty sure the file itself is outdated and you might also need to run "update from source code", so be sure to do that too!

**Comment by thescs** [comment]
> Use gettext-compatible translation software (Poedit works great), load .pot file into it and then use "create new translation" option, then save the translation as the file name you mentioned, then it "should" work. I'm pretty sure the file itself is outdated and you might also need to run "update from source code", so be sure to do that too!

This helped me, thanks!
