### ISSUE TITLE
deploy using Docker

### ISSUE THREAD

**Issue by dfyzicka** [jacklul/inlinegamesbot#36]
Hello, please help me launch it using Docker, as my PHP knowledge is not sufficient to figure it out myself.

**Comment by jacklul** [comment]
I don't provide support for running this on anything else than I provided files and configs for, I do not plan on expanding supported platforms.

I barely have any Docker knowledge and I'm afraid I will be of no use. You could take a look on fly.io deployment as they are using Docker images under the hood, maybe you will be able to figure out how to build it!
