### ISSUE TITLE
Message.pot

### ISSUE THREAD

**Issue by JamesTheFlash22** [jacklul/inlinegamesbot#38]
Hi, how can I set the language of translation?

**Comment by jacklul** [comment]
Use Poedit to load the POT file and there should be a button to create new translation, do the translation and then save file as messages.LANGUAGE_CODE.po (for example messages.pl.po).

**Comment by JamesTheFlash22** [comment]
ok

**Comment by JamesTheFlash22** [comment]
thanks

**Comment by JamesTheFlash22** [comment]
not .pot?

**Comment by jacklul** [comment]
> PO files: PO files are the files which contain the actual translations. Each language will have its own PO file, for example, for French there would be a fr.po file, for german there would be a de.po, for American English there might be en-US.po.
> 
> POT file: POT files are the template files for PO files. They will have all the translation strings left empty. A POT file is essentially an empty PO file without the translations, with just the original strings.

**Comment by JamesTheFlash22** [comment]
Ok thanks bye

Il mer 6 mar 2024, 18:26 jacklul ***@***.***> ha scritto:
