### ISSUE TITLE
inlinegamesbot still disabled(?)

### ISSUE THREAD

**Issue by edm0nd** [jacklul/inlinegamesbot#4]
it said"Disabled and under maintenance due to some issues!
Sorry!"

is it being fixed?

thanks

**Comment by jacklul** [comment]
I can literally do nothing as the issue is not on my end.

**Comment by edm0nd** [comment]
so could it back online in future times?
(cuz i dun know is telegram problem or some issue that have to wait to get fixed)

**Comment by jacklul** [comment]
@edm0nd The issue is that there is currently no network route to telegram API from my server, and since I have no other place to host it yet it will remain offline until the routing fixes itself.

**Comment by edm0nd** [comment]
Got it 

thanks for the reply :+1:
