### ISSUE TITLE
Rock Paper Scissors Score

### ISSUE THREAD

**Issue by DO97** [jacklul/inlinegamesbot#7]
In the previous versions of the game, the bot provided the score of the match "1-2, 2-2, etc." Why this feature has been removed?

**Comment by jacklul** [comment]
Implemented in commit https://github.com/jacklul/inlinegamesbot/commit/6fb537de09471e8298ffb185a4b5ecc43f0d8f0b.

Should now be live.

**Comment by DO97** [comment]
Yes. Thank you.
