### ISSUE TITLE
Rock-Paper-Scissors-Lizard-Spock

### ISSUE THREAD

**Issue by DO97** [jacklul/inlinegamesbot#9]
Is it possible to add this game, please?
https://en.wikipedia.org/wiki/Rock%E2%80%93paper%E2%80%93scissors?wprov=sfla1
I think it's easy to create, just add Lizard  (👌 or 🦎) and Spock (🖖) combinations to the current RPS code.

**Comment by jacklul** [comment]
I have never heard about this game variant...
Any source on this?

**Comment by DO97** [comment]
One popular five-weapon expansion is "rock-paper-scissors-Spock-lizard", invented by Sam Kass and Karen Bryla, which adds "Spock" and "lizard" to the standard three choices. "Spock" is signified with the Star Trek Vulcan salute, while "lizard" is shown by forming the hand into a sock-puppet-like mouth. Spock smashes scissors and vaporizes rock; he is poisoned by lizard and disproven by paper. Lizard poisons Spock and eats paper; it is crushed by rock and decapitated by scissors. This variant was mentioned in a 2005 article in The Times of London and was later the subject of an episode of the American sitcom The Big Bang Theory in 2008 (as rock-paper-scissors-lizard-Spock).

**Comment by DO97** [comment]
From the link above.

**Comment by DO97** [comment]
I think it would be cool. More possible combinations, more fun.
"👌" it's preferable for lizard.
